include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

linter:
  rules:
    # Every public API of a published package should be documented.
    - public_member_api_docs

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
